### ISSUE TITLE
Initial Editor Checklist

### ISSUE THREAD

**Issue by jsndyks** [journalovi/2024-luong-graphical-models#1]
- [x] Article uses a format something similar to the template
- [x] Includes author information
- [x] Includes abstract
- [x] Includes the required paper sections
   - [x] Table of contents
   - [x] Research materials
   - [x] Authorship
   - [x] License
   - [x] Conflicts of Interest
- [x] All figures have alt texts that describe the content non-visually
- [x] Add a notice infobox at the top that the paper is under review w/ link to github issues above the abstract. In Quarto this looks like:
   ```
   ::: {.callout-important appearance="simple"}
   ## Under Review {.unnumbered}
   This paper is under review on the experimental track of the [Journal of Visualization and Interaction](https://www.journalovi.org/).
   :::
   ```
- [x] Set up github pages
   - [x] Settings -> Actions -> General -> Allow journalovi, and select non-journalovi, actions. Enter: 
      `actions/*,quarto-dev/*`
      ![image](https://github.com/journalovi/2023-park-gatherplots/assets/6345019/05018b2f-f00e-4019-92de-cced0aab0d72)
   - [x] If using Quarto:
      - [x] clone the repo locally
      - [x] run this command in the repo directory:
         ```
         quarto publish gh-pages index.qmd
         ```
- [x] From the main repo page, click the settings gear icon next to "About" on the right. 
   - [x] Under "Description" enter "UNDER REVIEW"
   - [x] Under "Website" tick "Use Your Github Pages Website".
- [x] Verify the publishing workflow works. On the repo page, go to Actions and click on the "XXX Publish" (XXX = Quarto/Idyll/etc) workflow on the left, then click Run Workflow and run it.
   - [x] When this completes, check that the "pages build and deployment" action is successful.
   - [x] Check that the article is visible at the github.io address.
- [x] Edit README.md and add the following at the very top:
   ````
   ```diff
   ! This paper is under review on the experimental track of the Journal of Visualization and Interaction.
   ```
   ````
- [x] #3
  - [x] Check they are in appropriate long-term repositories (e.g. OSF, Zenodo, etc). Github repositories are okay as long as they are also archived on something like OSF or Zenodo. One easy way to archive + DOI an existing github repo is with Zenodo; see [here](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content)
  - [x] Check they are listed in the abstract and the required Materials section of the paper
- [x] If anything in the above list is missing (required paper sections, supplemental materials, etc), create an issue tagging the authors and ask them to add those materials (do this after sending them the intial review email).

- [x] All contents are displayed as in the author's original compiled version

**Comment by chatchavan** [comment]
JoVI template: https://www.journalovi.org/jovi-template-quarto/

**Comment by jsndyks** [comment]
* @chatchavan to edit README.md
* SuppMaterials check to be completed by SuppMaterials chair.
* @chatchavan adds "contents are displayed as in the author's original compiled version" checkbox

**Comment by chatchavan** [comment]
@vuluongj20 

- [ ] Fix the path prefix to work with the following URL `https://www.journalovi.org/2024-luong-graphical-models/` (or ideally any URL prefix.

- [ ] Add the following HTML block at the top of the page

```
 <p><strong>Under Review:</strong> This paper is <a href="https://www.journalovi.org/under-review.html">under review</a> on the experimental track of the <a href="https://www.journalovi.org/">Journal of Visualization and Interaction</a>. See the <a href="">reviewing process</a>.</p>
```

**Comment by mjskay** [comment]
@chatchavan @jsndyks I am not sure github pages is fully set up here: since this is a compiled site, we'll need a github workflow that runs the `yarn` commands listed in the README and copies the output folder to the `gh-pages` branch. The publish.yml workflow we use for idyll papers (listed in the experimental track Google doc) should be able to be adapted for this.

Note to OC: update checklist to include check for workflow on compiled papers (ie anything that is not static html)

**Comment by jsndyks** [comment]
Thanks @mjskay - should we make that an issue?

**Comment by jsndyks** [comment]
Waiting on 👆 "_all contents are displayed..._", otherwise ...

 * Abstract _exists_ but is very introductory and does not make results, claims or scope at all clear. It’s not structured as suggested in the JoVI template: [https://www.journalovi.org/jovi-template-quarto/](https://www.journalovi.org/jovi-template-quarto/)
* No _Table of Contents_ - how much does that matter?
* I checked ‘_All figures have alt texts that describe the content non-visually_’ as this is now a job for <code>[accessibility@journalovi.org](mailto:accessibility@journalovi.org)</code> in the new checklist

**Comment by mjskay** [comment]
Publishing should work now.

Since there are a number of other comments on this chain with different folks' responsibilities, I'd recommend moving them all into separate issues so that discussion is easier to follow.

**Comment by jsndyks** [comment]
> Publishing should work now.
> 
> Since there are a number of other comments on this chain with different folks' responsibilities, I'd recommend moving them all into separate issues so that discussion is easier to follow.

OK - so is the intention that the 'parent' issue spawns offspring issues? aAnd if so os there a way of modelling that (so that 'parent' can't be resolved until offspring are fixed?) Or is that too complicated and we keep it flat? (with the risk that parent will be closed before offspring are closed?) 😬

**Comment by chatchavan** [comment]
Adding to Matt's comment: You can add reference to an issue by using the reference button (shown below) or type a hash sign follow by an issue number.

<img width="855" alt="Screenshot 2024-04-26 at 14 40 52" src="https://github.com/journalovi/2024-luong-graphical-models/assets/5571433/6e21acc2-da5c-4a17-98dc-aadad4e57ef8">

**Comment by jsndyks** [comment]
> * https://www.journalovi.org/2024-luong-graphical-models/

https://www.journalovi.org/2024-luong-graphical-models/?retry

> Publishing should work now.
> 
> Since there are a number of other comments on this chain with different folks' responsibilities, I'd recommend moving them all into separate issues so that discussion is easier to follow.

I still can't see the interactive stuff in here :
 * [https://www.journalovi.org/2024-luong-graphical-models/](https://www.journalovi.org/2024-luong-graphical-models/)

I cleared the cache, tried different browsers - is this what you thought you had fixed @mjskay ? Apols if not.

**Comment by mjskay** [comment]
> I cleared the cache, tried different browsers - is this what you thought you had fixed @mjskay ? Apols if not.

Ah sorry, I wasn't clear - I fixed the setup so that if you make changes to the source code of the article and commit them to the main branch, the live version of the paper will automatically be recompiled. 

However, the javascript is still broken because the root path used to generate links to assets (like scripts) seems to be hard coded. I think @chatchavan opened an issue for @vuluongj20 to correct this (#4) but perhaps they should be poked more explicitly about it.

**Comment by mjskay** [comment]
(yeah looking at #4 it could be clearer about whose responsibility it is and that it is necessary for review to proceed)

**Comment by chatchavan** [comment]
I checked off the following points because they are completed and confirmed by the authors

* If anything in the above list is missing (required paper sections, supplemental materials, etc), create an issue tagging the authors and ask them to add those materials (do this after sending them the intial review email).

* All contents are displayed as in the author's original compiled version

**Comment by chatchavan** [comment]
The following point will be handled by Transparent Practices Chair. (It is currently assigned to me to ensure the handing over takes place.)

* Ensure all appropriate supplemental materials are included: e.g. experimental data, experimental analysis code, source code for artifacts, etc. For a full list of requirements see the transparency section of the author guide #3

**Comment by chatchavan** [comment]
Therefore, this issue can be closed by Jason.

**Comment by jsndyks** [comment]
@chatchavan and I agree that (at last!) all items are either completed or have a dedicated issue to track them.
